### ISSUE TITLE
How to activate

### ISSUE THREAD

**Issue by Berries72** [ozone10/Rainmeter-TranslucentRM#2]
Hello, this will sound silly but I could not find anywhere: where, in which file, on rainmeter do I place the option to activate TranslucentRM? Thanks

**Comment by ozone10** [comment]
@Berries72 
sorry for late reply, I did not notice.

It depends on what you want to use it on. For taskbar add it to some skin you use. For skin add it to it.

For more information and faster reply you better ask here https://forum.rainmeter.net/viewtopic.php?f=128&p=165921.
